services:
  - type: web
    name: pbs-backend
    env: ruby
    plan: free
    startCommand: "bundle exec puma -C config/puma.rb"
    buildCommand: "bundle install && bundle exec rails db:migrate && bundle exec rails db:seed"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RENDER_EXTERNAL_HOSTNAME
        value: pbs-backend.onrender.com

databases:
  - name: pbs-backend-db
    databaseName: pbs_backend_production
    user: pbs_backend
